/*
 * This file is generated by jOOQ.
 */
package com.theoxao.dura.orm.dto.tables.records;


import com.theoxao.dura.orm.dto.tables.TbIngRecipeRel;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbIngRecipeRelRecord extends TableRecordImpl<TbIngRecipeRelRecord> implements Record7<Integer, Integer, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_ing_recipe_rel.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public void setRid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public Integer getRid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public void setAmount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public String getAmount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public void setCat(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public String getCat() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public void setIid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public Integer getIid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.piid</code>.
     */
    public void setPiid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.piid</code>.
     */
    public Integer getPiid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, String, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.RID;
    }

    @Override
    public Field<String> field3() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.AMOUNT;
    }

    @Override
    public Field<String> field4() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.CAT;
    }

    @Override
    public Field<String> field5() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.NAME;
    }

    @Override
    public Field<Integer> field6() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.IID;
    }

    @Override
    public Field<Integer> field7() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.PIID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRid();
    }

    @Override
    public String component3() {
        return getAmount();
    }

    @Override
    public String component4() {
        return getCat();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public Integer component6() {
        return getIid();
    }

    @Override
    public Integer component7() {
        return getPiid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRid();
    }

    @Override
    public String value3() {
        return getAmount();
    }

    @Override
    public String value4() {
        return getCat();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public Integer value6() {
        return getIid();
    }

    @Override
    public Integer value7() {
        return getPiid();
    }

    @Override
    public TbIngRecipeRelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value2(Integer value) {
        setRid(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value3(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value4(String value) {
        setCat(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value6(Integer value) {
        setIid(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value7(Integer value) {
        setPiid(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbIngRecipeRelRecord
     */
    public TbIngRecipeRelRecord() {
        super(TbIngRecipeRel.TB_ING_RECIPE_REL);
    }

    /**
     * Create a detached, initialised TbIngRecipeRelRecord
     */
    public TbIngRecipeRelRecord(Integer id, Integer rid, String amount, String cat, String name, Integer iid, Integer piid) {
        super(TbIngRecipeRel.TB_ING_RECIPE_REL);

        setId(id);
        setRid(rid);
        setAmount(amount);
        setCat(cat);
        setName(name);
        setIid(iid);
        setPiid(piid);
    }
}
