/*
 * This file is generated by jOOQ.
 */
package com.theoxao.dura.orm.dto.tables.records;


import com.theoxao.dura.orm.dto.tables.TbRecipe;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbRecipeRecord extends UpdatableRecordImpl<TbRecipeRecord> implements Record21<Integer, String, JSON, JSON, String, String, String, JSON, LocalDateTime, JSON, JSON, JSON, LocalDateTime, LocalDateTime, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_recipe.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_recipe.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_recipe.desc</code>.
     */
    public void setDesc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_recipe.desc</code>.
     */
    public String getDesc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_recipe.difficulty</code>.
     */
    public void setDifficulty(JSON value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_recipe.difficulty</code>.
     */
    public JSON getDifficulty() {
        return (JSON) get(2);
    }

    /**
     * Setter for <code>public.tb_recipe.image</code>.
     */
    public void setImage(JSON value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_recipe.image</code>.
     */
    public JSON getImage() {
        return (JSON) get(3);
    }

    /**
     * Setter for <code>public.tb_recipe.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_recipe.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_recipe.summary</code>.
     */
    public void setSummary(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_recipe.summary</code>.
     */
    public String getSummary() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_recipe.tips</code>.
     */
    public void setTips(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_recipe.tips</code>.
     */
    public String getTips() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_recipe.label</code>.
     */
    public void setLabel(JSON value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tb_recipe.label</code>.
     */
    public JSON getLabel() {
        return (JSON) get(7);
    }

    /**
     * Setter for <code>public.tb_recipe.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tb_recipe.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.tb_recipe.ingredient</code>.
     */
    public void setIngredient(JSON value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tb_recipe.ingredient</code>.
     */
    public JSON getIngredient() {
        return (JSON) get(9);
    }

    /**
     * Setter for <code>public.tb_recipe.instruction</code>.
     */
    public void setInstruction(JSON value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tb_recipe.instruction</code>.
     */
    public JSON getInstruction() {
        return (JSON) get(10);
    }

    /**
     * Setter for <code>public.tb_recipe.duration</code>.
     */
    public void setDuration(JSON value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tb_recipe.duration</code>.
     */
    public JSON getDuration() {
        return (JSON) get(11);
    }

    /**
     * Setter for <code>public.tb_recipe.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tb_recipe.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.tb_recipe.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tb_recipe.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.tb_recipe.author_name</code>.
     */
    public void setAuthorName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tb_recipe.author_name</code>.
     */
    public String getAuthorName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tb_recipe.author_id</code>.
     */
    public void setAuthorId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tb_recipe.author_id</code>.
     */
    public String getAuthorId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.tb_recipe.pv</code>.
     */
    public void setPv(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tb_recipe.pv</code>.
     */
    public String getPv() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.tb_recipe.comment</code>.
     */
    public void setComment(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tb_recipe.comment</code>.
     */
    public String getComment() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.tb_recipe.cooked</code>.
     */
    public void setCooked(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tb_recipe.cooked</code>.
     */
    public String getCooked() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.tb_recipe.collect</code>.
     */
    public void setCollect(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tb_recipe.collect</code>.
     */
    public String getCollect() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.tb_recipe.status</code>.
     */
    public void setStatus(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tb_recipe.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, JSON, JSON, String, String, String, JSON, LocalDateTime, JSON, JSON, JSON, LocalDateTime, LocalDateTime, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, String, JSON, JSON, String, String, String, JSON, LocalDateTime, JSON, JSON, JSON, LocalDateTime, LocalDateTime, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbRecipe.TB_RECIPE.ID;
    }

    @Override
    public Field<String> field2() {
        return TbRecipe.TB_RECIPE.DESC;
    }

    @Override
    public Field<JSON> field3() {
        return TbRecipe.TB_RECIPE.DIFFICULTY;
    }

    @Override
    public Field<JSON> field4() {
        return TbRecipe.TB_RECIPE.IMAGE;
    }

    @Override
    public Field<String> field5() {
        return TbRecipe.TB_RECIPE.NAME;
    }

    @Override
    public Field<String> field6() {
        return TbRecipe.TB_RECIPE.SUMMARY;
    }

    @Override
    public Field<String> field7() {
        return TbRecipe.TB_RECIPE.TIPS;
    }

    @Override
    public Field<JSON> field8() {
        return TbRecipe.TB_RECIPE.LABEL;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TbRecipe.TB_RECIPE.CREATE_TIME;
    }

    @Override
    public Field<JSON> field10() {
        return TbRecipe.TB_RECIPE.INGREDIENT;
    }

    @Override
    public Field<JSON> field11() {
        return TbRecipe.TB_RECIPE.INSTRUCTION;
    }

    @Override
    public Field<JSON> field12() {
        return TbRecipe.TB_RECIPE.DURATION;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return TbRecipe.TB_RECIPE.INSERT_TIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return TbRecipe.TB_RECIPE.UPDATE_TIME;
    }

    @Override
    public Field<String> field15() {
        return TbRecipe.TB_RECIPE.AUTHOR_NAME;
    }

    @Override
    public Field<String> field16() {
        return TbRecipe.TB_RECIPE.AUTHOR_ID;
    }

    @Override
    public Field<String> field17() {
        return TbRecipe.TB_RECIPE.PV;
    }

    @Override
    public Field<String> field18() {
        return TbRecipe.TB_RECIPE.COMMENT;
    }

    @Override
    public Field<String> field19() {
        return TbRecipe.TB_RECIPE.COOKED;
    }

    @Override
    public Field<String> field20() {
        return TbRecipe.TB_RECIPE.COLLECT;
    }

    @Override
    public Field<Integer> field21() {
        return TbRecipe.TB_RECIPE.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDesc();
    }

    @Override
    public JSON component3() {
        return getDifficulty();
    }

    @Override
    public JSON component4() {
        return getImage();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getSummary();
    }

    @Override
    public String component7() {
        return getTips();
    }

    @Override
    public JSON component8() {
        return getLabel();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public JSON component10() {
        return getIngredient();
    }

    @Override
    public JSON component11() {
        return getInstruction();
    }

    @Override
    public JSON component12() {
        return getDuration();
    }

    @Override
    public LocalDateTime component13() {
        return getInsertTime();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdateTime();
    }

    @Override
    public String component15() {
        return getAuthorName();
    }

    @Override
    public String component16() {
        return getAuthorId();
    }

    @Override
    public String component17() {
        return getPv();
    }

    @Override
    public String component18() {
        return getComment();
    }

    @Override
    public String component19() {
        return getCooked();
    }

    @Override
    public String component20() {
        return getCollect();
    }

    @Override
    public Integer component21() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDesc();
    }

    @Override
    public JSON value3() {
        return getDifficulty();
    }

    @Override
    public JSON value4() {
        return getImage();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getSummary();
    }

    @Override
    public String value7() {
        return getTips();
    }

    @Override
    public JSON value8() {
        return getLabel();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public JSON value10() {
        return getIngredient();
    }

    @Override
    public JSON value11() {
        return getInstruction();
    }

    @Override
    public JSON value12() {
        return getDuration();
    }

    @Override
    public LocalDateTime value13() {
        return getInsertTime();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdateTime();
    }

    @Override
    public String value15() {
        return getAuthorName();
    }

    @Override
    public String value16() {
        return getAuthorId();
    }

    @Override
    public String value17() {
        return getPv();
    }

    @Override
    public String value18() {
        return getComment();
    }

    @Override
    public String value19() {
        return getCooked();
    }

    @Override
    public String value20() {
        return getCollect();
    }

    @Override
    public Integer value21() {
        return getStatus();
    }

    @Override
    public TbRecipeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbRecipeRecord value2(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public TbRecipeRecord value3(JSON value) {
        setDifficulty(value);
        return this;
    }

    @Override
    public TbRecipeRecord value4(JSON value) {
        setImage(value);
        return this;
    }

    @Override
    public TbRecipeRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbRecipeRecord value6(String value) {
        setSummary(value);
        return this;
    }

    @Override
    public TbRecipeRecord value7(String value) {
        setTips(value);
        return this;
    }

    @Override
    public TbRecipeRecord value8(JSON value) {
        setLabel(value);
        return this;
    }

    @Override
    public TbRecipeRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TbRecipeRecord value10(JSON value) {
        setIngredient(value);
        return this;
    }

    @Override
    public TbRecipeRecord value11(JSON value) {
        setInstruction(value);
        return this;
    }

    @Override
    public TbRecipeRecord value12(JSON value) {
        setDuration(value);
        return this;
    }

    @Override
    public TbRecipeRecord value13(LocalDateTime value) {
        setInsertTime(value);
        return this;
    }

    @Override
    public TbRecipeRecord value14(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TbRecipeRecord value15(String value) {
        setAuthorName(value);
        return this;
    }

    @Override
    public TbRecipeRecord value16(String value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public TbRecipeRecord value17(String value) {
        setPv(value);
        return this;
    }

    @Override
    public TbRecipeRecord value18(String value) {
        setComment(value);
        return this;
    }

    @Override
    public TbRecipeRecord value19(String value) {
        setCooked(value);
        return this;
    }

    @Override
    public TbRecipeRecord value20(String value) {
        setCollect(value);
        return this;
    }

    @Override
    public TbRecipeRecord value21(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public TbRecipeRecord values(Integer value1, String value2, JSON value3, JSON value4, String value5, String value6, String value7, JSON value8, LocalDateTime value9, JSON value10, JSON value11, JSON value12, LocalDateTime value13, LocalDateTime value14, String value15, String value16, String value17, String value18, String value19, String value20, Integer value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbRecipeRecord
     */
    public TbRecipeRecord() {
        super(TbRecipe.TB_RECIPE);
    }

    /**
     * Create a detached, initialised TbRecipeRecord
     */
    public TbRecipeRecord(Integer id, String desc, JSON difficulty, JSON image, String name, String summary, String tips, JSON label, LocalDateTime createTime, JSON ingredient, JSON instruction, JSON duration, LocalDateTime insertTime, LocalDateTime updateTime, String authorName, String authorId, String pv, String comment, String cooked, String collect, Integer status) {
        super(TbRecipe.TB_RECIPE);

        setId(id);
        setDesc(desc);
        setDifficulty(difficulty);
        setImage(image);
        setName(name);
        setSummary(summary);
        setTips(tips);
        setLabel(label);
        setCreateTime(createTime);
        setIngredient(ingredient);
        setInstruction(instruction);
        setDuration(duration);
        setInsertTime(insertTime);
        setUpdateTime(updateTime);
        setAuthorName(authorName);
        setAuthorId(authorId);
        setPv(pv);
        setComment(comment);
        setCooked(cooked);
        setCollect(collect);
        setStatus(status);
    }
}
