/*
 * This file is generated by jOOQ.
 */
package com.theoxao.dura.orm.dto.tables.records;


import com.theoxao.dura.orm.dto.tables.TbStorage;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbStorageRecord extends UpdatableRecordImpl<TbStorageRecord> implements Record3<Integer, String, JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_storage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_storage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_storage.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_storage.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_storage.cates</code>.
     */
    public void setCates(JSON value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_storage.cates</code>.
     */
    public JSON getCates() {
        return (JSON) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, JSON> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, JSON> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbStorage.TB_STORAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return TbStorage.TB_STORAGE.NAME;
    }

    @Override
    public Field<JSON> field3() {
        return TbStorage.TB_STORAGE.CATES;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public JSON component3() {
        return getCates();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public JSON value3() {
        return getCates();
    }

    @Override
    public TbStorageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbStorageRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbStorageRecord value3(JSON value) {
        setCates(value);
        return this;
    }

    @Override
    public TbStorageRecord values(Integer value1, String value2, JSON value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbStorageRecord
     */
    public TbStorageRecord() {
        super(TbStorage.TB_STORAGE);
    }

    /**
     * Create a detached, initialised TbStorageRecord
     */
    public TbStorageRecord(Integer id, String name, JSON cates) {
        super(TbStorage.TB_STORAGE);

        setId(id);
        setName(name);
        setCates(cates);
    }
}
