/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables;


import com.theoxao.duraemon.orm.dto.Public;
import com.theoxao.duraemon.orm.dto.tables.records.TbCategoryRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCategory extends TableImpl<TbCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tb_category</code>
     */
    public static final TbCategory TB_CATEGORY = new TbCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbCategoryRecord> getRecordType() {
        return TbCategoryRecord.class;
    }

    /**
     * The column <code>public.tb_category.id</code>.
     */
    public final TableField<TbCategoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.tb_category.name</code>.
     */
    public final TableField<TbCategoryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_category.level</code>.
     */
    public final TableField<TbCategoryRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tb_category.pid</code>.
     */
    public final TableField<TbCategoryRecord, Integer> PID = createField(DSL.name("pid"), SQLDataType.INTEGER, this, "");

    private TbCategory(Name alias, Table<TbCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbCategory(Name alias, Table<TbCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tb_category</code> table reference
     */
    public TbCategory(String alias) {
        this(DSL.name(alias), TB_CATEGORY);
    }

    /**
     * Create an aliased <code>public.tb_category</code> table reference
     */
    public TbCategory(Name alias) {
        this(alias, TB_CATEGORY);
    }

    /**
     * Create a <code>public.tb_category</code> table reference
     */
    public TbCategory() {
        this(DSL.name("tb_category"), null);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<TbCategoryRecord, Integer> getIdentity() {
        return (Identity<TbCategoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TbCategoryRecord> getPrimaryKey() {
        return Internal.createUniqueKey(TbCategory.TB_CATEGORY, DSL.name("tb_category_pkey"), new TableField[] { TbCategory.TB_CATEGORY.ID }, true);
    }

    @Override
    public List<UniqueKey<TbCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<TbCategoryRecord>>asList(
              Internal.createUniqueKey(TbCategory.TB_CATEGORY, DSL.name("tb_category_pkey"), new TableField[] { TbCategory.TB_CATEGORY.ID }, true)
        );
    }

    @Override
    public TbCategory as(String alias) {
        return new TbCategory(DSL.name(alias), this);
    }

    @Override
    public TbCategory as(Name alias) {
        return new TbCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCategory rename(String name) {
        return new TbCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCategory rename(Name name) {
        return new TbCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
