/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto;


import com.theoxao.duraemon.orm.dto.tables.RecipeJson;
import com.theoxao.duraemon.orm.dto.tables.TbCategory;
import com.theoxao.duraemon.orm.dto.tables.TbGoods;
import com.theoxao.duraemon.orm.dto.tables.TbItem;
import com.theoxao.duraemon.orm.dto.tables.TbRecipe;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.recipe_json</code>.
     */
    public final RecipeJson RECIPE_JSON = RecipeJson.RECIPE_JSON;

    /**
     * The table <code>public.tb_category</code>.
     */
    public final TbCategory TB_CATEGORY = TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_goods</code>.
     */
    public final TbGoods TB_GOODS = TbGoods.TB_GOODS;

    /**
     * The table <code>public.tb_item</code>.
     */
    public final TbItem TB_ITEM = TbItem.TB_ITEM;

    /**
     * The table <code>public.tb_recipe</code>.
     */
    public final TbRecipe TB_RECIPE = TbRecipe.TB_RECIPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            RecipeJson.RECIPE_JSON,
            TbCategory.TB_CATEGORY,
            TbGoods.TB_GOODS,
            TbItem.TB_ITEM,
            TbRecipe.TB_RECIPE);
    }
}
