/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto;


import com.theoxao.duraemon.orm.dto.tables.Ing;
import com.theoxao.duraemon.orm.dto.tables.TbCategory;
import com.theoxao.duraemon.orm.dto.tables.TbGoodCandidate;
import com.theoxao.duraemon.orm.dto.tables.TbGoods;
import com.theoxao.duraemon.orm.dto.tables.TbIngRecipeRel;
import com.theoxao.duraemon.orm.dto.tables.TbIngredient;
import com.theoxao.duraemon.orm.dto.tables.TbItem;
import com.theoxao.duraemon.orm.dto.tables.TbItemDetail;
import com.theoxao.duraemon.orm.dto.tables.TbLocation;
import com.theoxao.duraemon.orm.dto.tables.TbRecipe;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ing</code>.
     */
    public static final Ing ING = Ing.ING;

    /**
     * The table <code>public.tb_category</code>.
     */
    public static final TbCategory TB_CATEGORY = TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_good_candidate</code>.
     */
    public static final TbGoodCandidate TB_GOOD_CANDIDATE = TbGoodCandidate.TB_GOOD_CANDIDATE;

    /**
     * The table <code>public.tb_goods</code>.
     */
    public static final TbGoods TB_GOODS = TbGoods.TB_GOODS;

    /**
     * The table <code>public.tb_ing_recipe_rel</code>.
     */
    public static final TbIngRecipeRel TB_ING_RECIPE_REL = TbIngRecipeRel.TB_ING_RECIPE_REL;

    /**
     * The table <code>public.tb_ingredient</code>.
     */
    public static final TbIngredient TB_INGREDIENT = TbIngredient.TB_INGREDIENT;

    /**
     * The table <code>public.tb_item</code>.
     */
    public static final TbItem TB_ITEM = TbItem.TB_ITEM;

    /**
     * The table <code>public.tb_item_detail</code>.
     */
    public static final TbItemDetail TB_ITEM_DETAIL = TbItemDetail.TB_ITEM_DETAIL;

    /**
     * The table <code>public.tb_location</code>.
     */
    public static final TbLocation TB_LOCATION = TbLocation.TB_LOCATION;

    /**
     * The table <code>public.tb_recipe</code>.
     */
    public static final TbRecipe TB_RECIPE = TbRecipe.TB_RECIPE;
}
