/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto;


import com.theoxao.duraemon.orm.dto.tables.RecipeJson;
import com.theoxao.duraemon.orm.dto.tables.TbCategory;
import com.theoxao.duraemon.orm.dto.tables.TbGoods;
import com.theoxao.duraemon.orm.dto.tables.TbItem;
import com.theoxao.duraemon.orm.dto.tables.TbRecipe;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.recipe_json</code>.
     */
    public static final RecipeJson RECIPE_JSON = RecipeJson.RECIPE_JSON;

    /**
     * The table <code>public.tb_category</code>.
     */
    public static final TbCategory TB_CATEGORY = TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_goods</code>.
     */
    public static final TbGoods TB_GOODS = TbGoods.TB_GOODS;

    /**
     * The table <code>public.tb_item</code>.
     */
    public static final TbItem TB_ITEM = TbItem.TB_ITEM;

    /**
     * The table <code>public.tb_recipe</code>.
     */
    public static final TbRecipe TB_RECIPE = TbRecipe.TB_RECIPE;
}
