/*
 * This file is generated by jOOQ.
 */
package com.theoxao.dura.orm.dto.tables.pojos;


import java.io.Serializable;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbBrand implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private JSON    cate;
    private Integer itemCount;

    public TbBrand() {}

    public TbBrand(TbBrand value) {
        this.id = value.id;
        this.name = value.name;
        this.cate = value.cate;
        this.itemCount = value.itemCount;
    }

    public TbBrand(
        Integer id,
        String  name,
        JSON    cate,
        Integer itemCount
    ) {
        this.id = id;
        this.name = name;
        this.cate = cate;
        this.itemCount = itemCount;
    }

    /**
     * Getter for <code>public.tb_brand.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tb_brand.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tb_brand.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tb_brand.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.tb_brand.cate</code>.
     */
    public JSON getCate() {
        return this.cate;
    }

    /**
     * Setter for <code>public.tb_brand.cate</code>.
     */
    public void setCate(JSON cate) {
        this.cate = cate;
    }

    /**
     * Getter for <code>public.tb_brand.item_count</code>.
     */
    public Integer getItemCount() {
        return this.itemCount;
    }

    /**
     * Setter for <code>public.tb_brand.item_count</code>.
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbBrand (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(cate);
        sb.append(", ").append(itemCount);

        sb.append(")");
        return sb.toString();
    }
}
