server:
  port: 8989
spring:
  application:
    name: good
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/duraemon?useSSL=false&characterEncoding=utf8
      username: postgres
      password: ${MONGO_PASSWORD}
    url: jdbc:postgresql://127.0.0.1:5432/duraemon?useSSL=false&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver

duraemon:
  filePath: /data/static/duraemon