server:
  port: 8989
spring:
  application:
    name: good
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://www.theoxao.com:5432/duraemon?useSSL=false&characterEncoding=utf8
      username: postgres
      password: ${MONGO_PASSWORD}
    url: jdbc:postgresql://www.theoxao.com:5432/duraemon?useSSL=false&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      authentication-database: admin
      host: 172.29.198.83
      username: admin
      password: ${MONGO_PASSWORD}
      database: duraemon