server:
  port: 8989
spring:
  application:
    name: good
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://106.12.81.91:5432/dura?useSSL=false&characterEncoding=utf8
      username: postgres
      password: ${MONGO_PASSWORD}
    url: jdbc:postgresql://106.12.81.91:5432/dura?useSSL=false&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

dura:
  filePath: /data/static/dura
  httpBase: https://static.theoxao.com/dura