/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageMapper implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        uuid;
    private Integer       oid;
    private String        imageUrl;
    private LocalDateTime insertTime;
    private Integer       type;
    private Boolean       download;

    public ImageMapper() {}

    public ImageMapper(ImageMapper value) {
        this.uuid = value.uuid;
        this.oid = value.oid;
        this.imageUrl = value.imageUrl;
        this.insertTime = value.insertTime;
        this.type = value.type;
        this.download = value.download;
    }

    public ImageMapper(
        String        uuid,
        Integer       oid,
        String        imageUrl,
        LocalDateTime insertTime,
        Integer       type,
        Boolean       download
    ) {
        this.uuid = uuid;
        this.oid = oid;
        this.imageUrl = imageUrl;
        this.insertTime = insertTime;
        this.type = type;
        this.download = download;
    }

    /**
     * Getter for <code>public.image_mapper.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.image_mapper.uuid</code>.
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>public.image_mapper.oid</code>.
     */
    public Integer getOid() {
        return this.oid;
    }

    /**
     * Setter for <code>public.image_mapper.oid</code>.
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * Getter for <code>public.image_mapper.image_url</code>.
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Setter for <code>public.image_mapper.image_url</code>.
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Getter for <code>public.image_mapper.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return this.insertTime;
    }

    /**
     * Setter for <code>public.image_mapper.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * Getter for <code>public.image_mapper.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.image_mapper.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.image_mapper.download</code>.
     */
    public Boolean getDownload() {
        return this.download;
    }

    /**
     * Setter for <code>public.image_mapper.download</code>.
     */
    public void setDownload(Boolean download) {
        this.download = download;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImageMapper (");

        sb.append(uuid);
        sb.append(", ").append(oid);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(insertTime);
        sb.append(", ").append(type);
        sb.append(", ").append(download);

        sb.append(")");
        return sb.toString();
    }
}
