/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ing implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private Long   cnt;

    public Ing() {}

    public Ing(Ing value) {
        this.name = value.name;
        this.cnt = value.cnt;
    }

    public Ing(
        String name,
        Long   cnt
    ) {
        this.name = name;
        this.cnt = cnt;
    }

    /**
     * Getter for <code>public.ing.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.ing.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.ing.cnt</code>.
     */
    public Long getCnt() {
        return this.cnt;
    }

    /**
     * Setter for <code>public.ing.cnt</code>.
     */
    public void setCnt(Long cnt) {
        this.cnt = cnt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ing (");

        sb.append(name);
        sb.append(", ").append(cnt);

        sb.append(")");
        return sb.toString();
    }
}
