/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeJson implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private JSON          json;
    private LocalDateTime insertTime;
    private Boolean       toObj;

    public RecipeJson() {}

    public RecipeJson(RecipeJson value) {
        this.id = value.id;
        this.json = value.json;
        this.insertTime = value.insertTime;
        this.toObj = value.toObj;
    }

    public RecipeJson(
        Integer       id,
        JSON          json,
        LocalDateTime insertTime,
        Boolean       toObj
    ) {
        this.id = id;
        this.json = json;
        this.insertTime = insertTime;
        this.toObj = toObj;
    }

    /**
     * Getter for <code>public.recipe_json.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.recipe_json.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.recipe_json.json</code>.
     */
    public JSON getJson() {
        return this.json;
    }

    /**
     * Setter for <code>public.recipe_json.json</code>.
     */
    public void setJson(JSON json) {
        this.json = json;
    }

    /**
     * Getter for <code>public.recipe_json.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return this.insertTime;
    }

    /**
     * Setter for <code>public.recipe_json.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * Getter for <code>public.recipe_json.to_obj</code>.
     */
    public Boolean getToObj() {
        return this.toObj;
    }

    /**
     * Setter for <code>public.recipe_json.to_obj</code>.
     */
    public void setToObj(Boolean toObj) {
        this.toObj = toObj;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecipeJson (");

        sb.append(id);
        sb.append(", ").append(json);
        sb.append(", ").append(insertTime);
        sb.append(", ").append(toObj);

        sb.append(")");
        return sb.toString();
    }
}
