/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbGoods implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private String        desc;
    private Integer       cate;
    private String        subCate;
    private Integer       remainBatch;
    private Integer       recentPrice;
    private JSON          images;
    private Integer       needBuy;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public TbGoods() {}

    public TbGoods(TbGoods value) {
        this.id = value.id;
        this.name = value.name;
        this.desc = value.desc;
        this.cate = value.cate;
        this.subCate = value.subCate;
        this.remainBatch = value.remainBatch;
        this.recentPrice = value.recentPrice;
        this.images = value.images;
        this.needBuy = value.needBuy;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TbGoods(
        Integer       id,
        String        name,
        String        desc,
        Integer       cate,
        String        subCate,
        Integer       remainBatch,
        Integer       recentPrice,
        JSON          images,
        Integer       needBuy,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.cate = cate;
        this.subCate = subCate;
        this.remainBatch = remainBatch;
        this.recentPrice = recentPrice;
        this.images = images;
        this.needBuy = needBuy;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>public.tb_goods.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tb_goods.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tb_goods.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tb_goods.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.tb_goods.desc</code>.
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>public.tb_goods.desc</code>.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>public.tb_goods.cate</code>.
     */
    public Integer getCate() {
        return this.cate;
    }

    /**
     * Setter for <code>public.tb_goods.cate</code>.
     */
    public void setCate(Integer cate) {
        this.cate = cate;
    }

    /**
     * Getter for <code>public.tb_goods.sub_cate</code>.
     */
    public String getSubCate() {
        return this.subCate;
    }

    /**
     * Setter for <code>public.tb_goods.sub_cate</code>.
     */
    public void setSubCate(String subCate) {
        this.subCate = subCate;
    }

    /**
     * Getter for <code>public.tb_goods.remain_batch</code>.
     */
    public Integer getRemainBatch() {
        return this.remainBatch;
    }

    /**
     * Setter for <code>public.tb_goods.remain_batch</code>.
     */
    public void setRemainBatch(Integer remainBatch) {
        this.remainBatch = remainBatch;
    }

    /**
     * Getter for <code>public.tb_goods.recent_price</code>.
     */
    public Integer getRecentPrice() {
        return this.recentPrice;
    }

    /**
     * Setter for <code>public.tb_goods.recent_price</code>.
     */
    public void setRecentPrice(Integer recentPrice) {
        this.recentPrice = recentPrice;
    }

    /**
     * Getter for <code>public.tb_goods.images</code>.
     */
    public JSON getImages() {
        return this.images;
    }

    /**
     * Setter for <code>public.tb_goods.images</code>.
     */
    public void setImages(JSON images) {
        this.images = images;
    }

    /**
     * Getter for <code>public.tb_goods.need_buy</code>.
     */
    public Integer getNeedBuy() {
        return this.needBuy;
    }

    /**
     * Setter for <code>public.tb_goods.need_buy</code>.
     */
    public void setNeedBuy(Integer needBuy) {
        this.needBuy = needBuy;
    }

    /**
     * Getter for <code>public.tb_goods.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>public.tb_goods.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>public.tb_goods.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>public.tb_goods.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbGoods (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);
        sb.append(", ").append(cate);
        sb.append(", ").append(subCate);
        sb.append(", ").append(remainBatch);
        sb.append(", ").append(recentPrice);
        sb.append(", ").append(images);
        sb.append(", ").append(needBuy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
