/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbIngRecipeRel implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer iid;
    private Integer rid;
    private String  amount;
    private String  cat;

    public TbIngRecipeRel() {}

    public TbIngRecipeRel(TbIngRecipeRel value) {
        this.iid = value.iid;
        this.rid = value.rid;
        this.amount = value.amount;
        this.cat = value.cat;
    }

    public TbIngRecipeRel(
        Integer iid,
        Integer rid,
        String  amount,
        String  cat
    ) {
        this.iid = iid;
        this.rid = rid;
        this.amount = amount;
        this.cat = cat;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public Integer getIid() {
        return this.iid;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public Integer getRid() {
        return this.rid;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public String getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public String getCat() {
        return this.cat;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public void setCat(String cat) {
        this.cat = cat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbIngRecipeRel (");

        sb.append(iid);
        sb.append(", ").append(rid);
        sb.append(", ").append(amount);
        sb.append(", ").append(cat);

        sb.append(")");
        return sb.toString();
    }
}
