/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbIngRecipeRel implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer rid;
    private String  amount;
    private String  cat;
    private String  name;

    public TbIngRecipeRel() {}

    public TbIngRecipeRel(TbIngRecipeRel value) {
        this.id = value.id;
        this.rid = value.rid;
        this.amount = value.amount;
        this.cat = value.cat;
        this.name = value.name;
    }

    public TbIngRecipeRel(
        Integer id,
        Integer rid,
        String  amount,
        String  cat,
        String  name
    ) {
        this.id = id;
        this.rid = rid;
        this.amount = amount;
        this.cat = cat;
        this.name = name;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public Integer getRid() {
        return this.rid;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public String getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public String getCat() {
        return this.cat;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public void setCat(String cat) {
        this.cat = cat;
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbIngRecipeRel (");

        sb.append(id);
        sb.append(", ").append(rid);
        sb.append(", ").append(amount);
        sb.append(", ").append(cat);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
