/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbRecipe implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        desc;
    private JSON          difficulty;
    private JSON          image;
    private String        name;
    private String        summary;
    private String        tips;
    private JSON          label;
    private LocalDateTime createTime;
    private JSON          ingredient;
    private JSON          instruction;
    private JSON          duration;
    private LocalDateTime insertTime;
    private LocalDateTime updateTime;
    private String        authorName;
    private String        authorId;
    private String        pv;
    private String        comment;
    private String        cooked;
    private String        collect;
    private Integer       status;

    public TbRecipe() {}

    public TbRecipe(TbRecipe value) {
        this.id = value.id;
        this.desc = value.desc;
        this.difficulty = value.difficulty;
        this.image = value.image;
        this.name = value.name;
        this.summary = value.summary;
        this.tips = value.tips;
        this.label = value.label;
        this.createTime = value.createTime;
        this.ingredient = value.ingredient;
        this.instruction = value.instruction;
        this.duration = value.duration;
        this.insertTime = value.insertTime;
        this.updateTime = value.updateTime;
        this.authorName = value.authorName;
        this.authorId = value.authorId;
        this.pv = value.pv;
        this.comment = value.comment;
        this.cooked = value.cooked;
        this.collect = value.collect;
        this.status = value.status;
    }

    public TbRecipe(
        Integer       id,
        String        desc,
        JSON          difficulty,
        JSON          image,
        String        name,
        String        summary,
        String        tips,
        JSON          label,
        LocalDateTime createTime,
        JSON          ingredient,
        JSON          instruction,
        JSON          duration,
        LocalDateTime insertTime,
        LocalDateTime updateTime,
        String        authorName,
        String        authorId,
        String        pv,
        String        comment,
        String        cooked,
        String        collect,
        Integer       status
    ) {
        this.id = id;
        this.desc = desc;
        this.difficulty = difficulty;
        this.image = image;
        this.name = name;
        this.summary = summary;
        this.tips = tips;
        this.label = label;
        this.createTime = createTime;
        this.ingredient = ingredient;
        this.instruction = instruction;
        this.duration = duration;
        this.insertTime = insertTime;
        this.updateTime = updateTime;
        this.authorName = authorName;
        this.authorId = authorId;
        this.pv = pv;
        this.comment = comment;
        this.cooked = cooked;
        this.collect = collect;
        this.status = status;
    }

    /**
     * Getter for <code>public.tb_recipe.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tb_recipe.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tb_recipe.desc</code>.
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>public.tb_recipe.desc</code>.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>public.tb_recipe.difficulty</code>.
     */
    public JSON getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>public.tb_recipe.difficulty</code>.
     */
    public void setDifficulty(JSON difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * Getter for <code>public.tb_recipe.image</code>.
     */
    public JSON getImage() {
        return this.image;
    }

    /**
     * Setter for <code>public.tb_recipe.image</code>.
     */
    public void setImage(JSON image) {
        this.image = image;
    }

    /**
     * Getter for <code>public.tb_recipe.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tb_recipe.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.tb_recipe.summary</code>.
     */
    public String getSummary() {
        return this.summary;
    }

    /**
     * Setter for <code>public.tb_recipe.summary</code>.
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for <code>public.tb_recipe.tips</code>.
     */
    public String getTips() {
        return this.tips;
    }

    /**
     * Setter for <code>public.tb_recipe.tips</code>.
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * Getter for <code>public.tb_recipe.label</code>.
     */
    public JSON getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>public.tb_recipe.label</code>.
     */
    public void setLabel(JSON label) {
        this.label = label;
    }

    /**
     * Getter for <code>public.tb_recipe.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>public.tb_recipe.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>public.tb_recipe.ingredient</code>.
     */
    public JSON getIngredient() {
        return this.ingredient;
    }

    /**
     * Setter for <code>public.tb_recipe.ingredient</code>.
     */
    public void setIngredient(JSON ingredient) {
        this.ingredient = ingredient;
    }

    /**
     * Getter for <code>public.tb_recipe.instruction</code>.
     */
    public JSON getInstruction() {
        return this.instruction;
    }

    /**
     * Setter for <code>public.tb_recipe.instruction</code>.
     */
    public void setInstruction(JSON instruction) {
        this.instruction = instruction;
    }

    /**
     * Getter for <code>public.tb_recipe.duration</code>.
     */
    public JSON getDuration() {
        return this.duration;
    }

    /**
     * Setter for <code>public.tb_recipe.duration</code>.
     */
    public void setDuration(JSON duration) {
        this.duration = duration;
    }

    /**
     * Getter for <code>public.tb_recipe.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return this.insertTime;
    }

    /**
     * Setter for <code>public.tb_recipe.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * Getter for <code>public.tb_recipe.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>public.tb_recipe.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>public.tb_recipe.author_name</code>.
     */
    public String getAuthorName() {
        return this.authorName;
    }

    /**
     * Setter for <code>public.tb_recipe.author_name</code>.
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * Getter for <code>public.tb_recipe.author_id</code>.
     */
    public String getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>public.tb_recipe.author_id</code>.
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * Getter for <code>public.tb_recipe.pv</code>.
     */
    public String getPv() {
        return this.pv;
    }

    /**
     * Setter for <code>public.tb_recipe.pv</code>.
     */
    public void setPv(String pv) {
        this.pv = pv;
    }

    /**
     * Getter for <code>public.tb_recipe.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>public.tb_recipe.comment</code>.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>public.tb_recipe.cooked</code>.
     */
    public String getCooked() {
        return this.cooked;
    }

    /**
     * Setter for <code>public.tb_recipe.cooked</code>.
     */
    public void setCooked(String cooked) {
        this.cooked = cooked;
    }

    /**
     * Getter for <code>public.tb_recipe.collect</code>.
     */
    public String getCollect() {
        return this.collect;
    }

    /**
     * Setter for <code>public.tb_recipe.collect</code>.
     */
    public void setCollect(String collect) {
        this.collect = collect;
    }

    /**
     * Getter for <code>public.tb_recipe.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.tb_recipe.status</code>.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbRecipe (");

        sb.append(id);
        sb.append(", ").append(desc);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(image);
        sb.append(", ").append(name);
        sb.append(", ").append(summary);
        sb.append(", ").append(tips);
        sb.append(", ").append(label);
        sb.append(", ").append(createTime);
        sb.append(", ").append(ingredient);
        sb.append(", ").append(instruction);
        sb.append(", ").append(duration);
        sb.append(", ").append(insertTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(authorName);
        sb.append(", ").append(authorId);
        sb.append(", ").append(pv);
        sb.append(", ").append(comment);
        sb.append(", ").append(cooked);
        sb.append(", ").append(collect);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
