/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbRecipe implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        desc;
    private JSON          difficulty;
    private String        ident;
    private JSON          image;
    private String        name;
    private JSON          photo;
    private String        score;
    private String        summary;
    private String        thumb;
    private String        tips;
    private String        url;
    private JSON          author;
    private JSON          label;
    private LocalDateTime createTime;
    private JSON          ingredient;
    private JSON          instruction;
    private JSON          duration;
    private JSON          recipeCats;
    private JSON          originalCate;
    private JSON          stats;
    private JSON          equipmentRelatedInfo;
    private String        videoUrl;
    private String        videoPageUrl;
    private JSON          coverMicroVideo;
    private JSON          vodVideo;
    private String        summaryDesc;
    private LocalDateTime insertTime;
    private LocalDateTime updateTime;

    public TbRecipe() {}

    public TbRecipe(TbRecipe value) {
        this.id = value.id;
        this.desc = value.desc;
        this.difficulty = value.difficulty;
        this.ident = value.ident;
        this.image = value.image;
        this.name = value.name;
        this.photo = value.photo;
        this.score = value.score;
        this.summary = value.summary;
        this.thumb = value.thumb;
        this.tips = value.tips;
        this.url = value.url;
        this.author = value.author;
        this.label = value.label;
        this.createTime = value.createTime;
        this.ingredient = value.ingredient;
        this.instruction = value.instruction;
        this.duration = value.duration;
        this.recipeCats = value.recipeCats;
        this.originalCate = value.originalCate;
        this.stats = value.stats;
        this.equipmentRelatedInfo = value.equipmentRelatedInfo;
        this.videoUrl = value.videoUrl;
        this.videoPageUrl = value.videoPageUrl;
        this.coverMicroVideo = value.coverMicroVideo;
        this.vodVideo = value.vodVideo;
        this.summaryDesc = value.summaryDesc;
        this.insertTime = value.insertTime;
        this.updateTime = value.updateTime;
    }

    public TbRecipe(
        Integer       id,
        String        desc,
        JSON          difficulty,
        String        ident,
        JSON          image,
        String        name,
        JSON          photo,
        String        score,
        String        summary,
        String        thumb,
        String        tips,
        String        url,
        JSON          author,
        JSON          label,
        LocalDateTime createTime,
        JSON          ingredient,
        JSON          instruction,
        JSON          duration,
        JSON          recipeCats,
        JSON          originalCate,
        JSON          stats,
        JSON          equipmentRelatedInfo,
        String        videoUrl,
        String        videoPageUrl,
        JSON          coverMicroVideo,
        JSON          vodVideo,
        String        summaryDesc,
        LocalDateTime insertTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.desc = desc;
        this.difficulty = difficulty;
        this.ident = ident;
        this.image = image;
        this.name = name;
        this.photo = photo;
        this.score = score;
        this.summary = summary;
        this.thumb = thumb;
        this.tips = tips;
        this.url = url;
        this.author = author;
        this.label = label;
        this.createTime = createTime;
        this.ingredient = ingredient;
        this.instruction = instruction;
        this.duration = duration;
        this.recipeCats = recipeCats;
        this.originalCate = originalCate;
        this.stats = stats;
        this.equipmentRelatedInfo = equipmentRelatedInfo;
        this.videoUrl = videoUrl;
        this.videoPageUrl = videoPageUrl;
        this.coverMicroVideo = coverMicroVideo;
        this.vodVideo = vodVideo;
        this.summaryDesc = summaryDesc;
        this.insertTime = insertTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>public.tb_recipe.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tb_recipe.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tb_recipe.desc</code>.
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>public.tb_recipe.desc</code>.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>public.tb_recipe.difficulty</code>.
     */
    public JSON getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>public.tb_recipe.difficulty</code>.
     */
    public void setDifficulty(JSON difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * Getter for <code>public.tb_recipe.ident</code>.
     */
    public String getIdent() {
        return this.ident;
    }

    /**
     * Setter for <code>public.tb_recipe.ident</code>.
     */
    public void setIdent(String ident) {
        this.ident = ident;
    }

    /**
     * Getter for <code>public.tb_recipe.image</code>.
     */
    public JSON getImage() {
        return this.image;
    }

    /**
     * Setter for <code>public.tb_recipe.image</code>.
     */
    public void setImage(JSON image) {
        this.image = image;
    }

    /**
     * Getter for <code>public.tb_recipe.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tb_recipe.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.tb_recipe.photo</code>.
     */
    public JSON getPhoto() {
        return this.photo;
    }

    /**
     * Setter for <code>public.tb_recipe.photo</code>.
     */
    public void setPhoto(JSON photo) {
        this.photo = photo;
    }

    /**
     * Getter for <code>public.tb_recipe.score</code>.
     */
    public String getScore() {
        return this.score;
    }

    /**
     * Setter for <code>public.tb_recipe.score</code>.
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * Getter for <code>public.tb_recipe.summary</code>.
     */
    public String getSummary() {
        return this.summary;
    }

    /**
     * Setter for <code>public.tb_recipe.summary</code>.
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for <code>public.tb_recipe.thumb</code>.
     */
    public String getThumb() {
        return this.thumb;
    }

    /**
     * Setter for <code>public.tb_recipe.thumb</code>.
     */
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    /**
     * Getter for <code>public.tb_recipe.tips</code>.
     */
    public String getTips() {
        return this.tips;
    }

    /**
     * Setter for <code>public.tb_recipe.tips</code>.
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * Getter for <code>public.tb_recipe.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.tb_recipe.url</code>.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.tb_recipe.author</code>.
     */
    public JSON getAuthor() {
        return this.author;
    }

    /**
     * Setter for <code>public.tb_recipe.author</code>.
     */
    public void setAuthor(JSON author) {
        this.author = author;
    }

    /**
     * Getter for <code>public.tb_recipe.label</code>.
     */
    public JSON getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>public.tb_recipe.label</code>.
     */
    public void setLabel(JSON label) {
        this.label = label;
    }

    /**
     * Getter for <code>public.tb_recipe.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>public.tb_recipe.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>public.tb_recipe.ingredient</code>.
     */
    public JSON getIngredient() {
        return this.ingredient;
    }

    /**
     * Setter for <code>public.tb_recipe.ingredient</code>.
     */
    public void setIngredient(JSON ingredient) {
        this.ingredient = ingredient;
    }

    /**
     * Getter for <code>public.tb_recipe.instruction</code>.
     */
    public JSON getInstruction() {
        return this.instruction;
    }

    /**
     * Setter for <code>public.tb_recipe.instruction</code>.
     */
    public void setInstruction(JSON instruction) {
        this.instruction = instruction;
    }

    /**
     * Getter for <code>public.tb_recipe.duration</code>.
     */
    public JSON getDuration() {
        return this.duration;
    }

    /**
     * Setter for <code>public.tb_recipe.duration</code>.
     */
    public void setDuration(JSON duration) {
        this.duration = duration;
    }

    /**
     * Getter for <code>public.tb_recipe.recipe_cats</code>.
     */
    public JSON getRecipeCats() {
        return this.recipeCats;
    }

    /**
     * Setter for <code>public.tb_recipe.recipe_cats</code>.
     */
    public void setRecipeCats(JSON recipeCats) {
        this.recipeCats = recipeCats;
    }

    /**
     * Getter for <code>public.tb_recipe.original_cate</code>.
     */
    public JSON getOriginalCate() {
        return this.originalCate;
    }

    /**
     * Setter for <code>public.tb_recipe.original_cate</code>.
     */
    public void setOriginalCate(JSON originalCate) {
        this.originalCate = originalCate;
    }

    /**
     * Getter for <code>public.tb_recipe.stats</code>.
     */
    public JSON getStats() {
        return this.stats;
    }

    /**
     * Setter for <code>public.tb_recipe.stats</code>.
     */
    public void setStats(JSON stats) {
        this.stats = stats;
    }

    /**
     * Getter for <code>public.tb_recipe.equipment_related_info</code>.
     */
    public JSON getEquipmentRelatedInfo() {
        return this.equipmentRelatedInfo;
    }

    /**
     * Setter for <code>public.tb_recipe.equipment_related_info</code>.
     */
    public void setEquipmentRelatedInfo(JSON equipmentRelatedInfo) {
        this.equipmentRelatedInfo = equipmentRelatedInfo;
    }

    /**
     * Getter for <code>public.tb_recipe.video_url</code>.
     */
    public String getVideoUrl() {
        return this.videoUrl;
    }

    /**
     * Setter for <code>public.tb_recipe.video_url</code>.
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * Getter for <code>public.tb_recipe.video_page_url</code>.
     */
    public String getVideoPageUrl() {
        return this.videoPageUrl;
    }

    /**
     * Setter for <code>public.tb_recipe.video_page_url</code>.
     */
    public void setVideoPageUrl(String videoPageUrl) {
        this.videoPageUrl = videoPageUrl;
    }

    /**
     * Getter for <code>public.tb_recipe.cover_micro_video</code>.
     */
    public JSON getCoverMicroVideo() {
        return this.coverMicroVideo;
    }

    /**
     * Setter for <code>public.tb_recipe.cover_micro_video</code>.
     */
    public void setCoverMicroVideo(JSON coverMicroVideo) {
        this.coverMicroVideo = coverMicroVideo;
    }

    /**
     * Getter for <code>public.tb_recipe.vod_video</code>.
     */
    public JSON getVodVideo() {
        return this.vodVideo;
    }

    /**
     * Setter for <code>public.tb_recipe.vod_video</code>.
     */
    public void setVodVideo(JSON vodVideo) {
        this.vodVideo = vodVideo;
    }

    /**
     * Getter for <code>public.tb_recipe.summary_desc</code>.
     */
    public String getSummaryDesc() {
        return this.summaryDesc;
    }

    /**
     * Setter for <code>public.tb_recipe.summary_desc</code>.
     */
    public void setSummaryDesc(String summaryDesc) {
        this.summaryDesc = summaryDesc;
    }

    /**
     * Getter for <code>public.tb_recipe.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return this.insertTime;
    }

    /**
     * Setter for <code>public.tb_recipe.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * Getter for <code>public.tb_recipe.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>public.tb_recipe.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbRecipe (");

        sb.append(id);
        sb.append(", ").append(desc);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(ident);
        sb.append(", ").append(image);
        sb.append(", ").append(name);
        sb.append(", ").append(photo);
        sb.append(", ").append(score);
        sb.append(", ").append(summary);
        sb.append(", ").append(thumb);
        sb.append(", ").append(tips);
        sb.append(", ").append(url);
        sb.append(", ").append(author);
        sb.append(", ").append(label);
        sb.append(", ").append(createTime);
        sb.append(", ").append(ingredient);
        sb.append(", ").append(instruction);
        sb.append(", ").append(duration);
        sb.append(", ").append(recipeCats);
        sb.append(", ").append(originalCate);
        sb.append(", ").append(stats);
        sb.append(", ").append(equipmentRelatedInfo);
        sb.append(", ").append(videoUrl);
        sb.append(", ").append(videoPageUrl);
        sb.append(", ").append(coverMicroVideo);
        sb.append(", ").append(vodVideo);
        sb.append(", ").append(summaryDesc);
        sb.append(", ").append(insertTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
