/*
 * This file is generated by jOOQ.
 */
package com.theoxao.dura.orm.dto.tables;


import com.theoxao.dura.orm.dto.Public;
import com.theoxao.dura.orm.dto.tables.records.TbRecipeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbRecipe extends TableImpl<TbRecipeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tb_recipe</code>
     */
    public static final TbRecipe TB_RECIPE = new TbRecipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbRecipeRecord> getRecordType() {
        return TbRecipeRecord.class;
    }

    /**
     * The column <code>public.tb_recipe.id</code>.
     */
    public final TableField<TbRecipeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tb_recipe.desc</code>.
     */
    public final TableField<TbRecipeRecord, String> DESC = createField(DSL.name("desc"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_recipe.difficulty</code>.
     */
    public final TableField<TbRecipeRecord, JSON> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.image</code>.
     */
    public final TableField<TbRecipeRecord, JSON> IMAGE = createField(DSL.name("image"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.name</code>.
     */
    public final TableField<TbRecipeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.tb_recipe.summary</code>.
     */
    public final TableField<TbRecipeRecord, String> SUMMARY = createField(DSL.name("summary"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_recipe.tips</code>.
     */
    public final TableField<TbRecipeRecord, String> TIPS = createField(DSL.name("tips"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_recipe.label</code>.
     */
    public final TableField<TbRecipeRecord, JSON> LABEL = createField(DSL.name("label"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.create_time</code>.
     */
    public final TableField<TbRecipeRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>public.tb_recipe.ingredient</code>.
     */
    public final TableField<TbRecipeRecord, JSON> INGREDIENT = createField(DSL.name("ingredient"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.instruction</code>.
     */
    public final TableField<TbRecipeRecord, JSON> INSTRUCTION = createField(DSL.name("instruction"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.duration</code>.
     */
    public final TableField<TbRecipeRecord, JSON> DURATION = createField(DSL.name("duration"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.tb_recipe.insert_time</code>.
     */
    public final TableField<TbRecipeRecord, LocalDateTime> INSERT_TIME = createField(DSL.name("insert_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.tb_recipe.update_time</code>.
     */
    public final TableField<TbRecipeRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.tb_recipe.author_name</code>.
     */
    public final TableField<TbRecipeRecord, String> AUTHOR_NAME = createField(DSL.name("author_name"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.tb_recipe.author_id</code>.
     */
    public final TableField<TbRecipeRecord, String> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.tb_recipe.pv</code>.
     */
    public final TableField<TbRecipeRecord, String> PV = createField(DSL.name("pv"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.tb_recipe.comment</code>.
     */
    public final TableField<TbRecipeRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.tb_recipe.cooked</code>.
     */
    public final TableField<TbRecipeRecord, String> COOKED = createField(DSL.name("cooked"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.tb_recipe.collect</code>.
     */
    public final TableField<TbRecipeRecord, String> COLLECT = createField(DSL.name("collect"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.tb_recipe.status</code>.
     */
    public final TableField<TbRecipeRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    private TbRecipe(Name alias, Table<TbRecipeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbRecipe(Name alias, Table<TbRecipeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tb_recipe</code> table reference
     */
    public TbRecipe(String alias) {
        this(DSL.name(alias), TB_RECIPE);
    }

    /**
     * Create an aliased <code>public.tb_recipe</code> table reference
     */
    public TbRecipe(Name alias) {
        this(alias, TB_RECIPE);
    }

    /**
     * Create a <code>public.tb_recipe</code> table reference
     */
    public TbRecipe() {
        this(DSL.name("tb_recipe"), null);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<TbRecipeRecord> getPrimaryKey() {
        return Internal.createUniqueKey(TbRecipe.TB_RECIPE, DSL.name("tb_recipe_copy1_pkey"), new TableField[] { TbRecipe.TB_RECIPE.ID }, true);
    }

    @Override
    public List<UniqueKey<TbRecipeRecord>> getKeys() {
        return Arrays.<UniqueKey<TbRecipeRecord>>asList(
              Internal.createUniqueKey(TbRecipe.TB_RECIPE, DSL.name("tb_recipe_copy1_pkey"), new TableField[] { TbRecipe.TB_RECIPE.ID }, true)
        );
    }

    @Override
    public TbRecipe as(String alias) {
        return new TbRecipe(DSL.name(alias), this);
    }

    @Override
    public TbRecipe as(Name alias) {
        return new TbRecipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbRecipe rename(String name) {
        return new TbRecipe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbRecipe rename(Name name) {
        return new TbRecipe(name, null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, JSON, JSON, String, String, String, JSON, LocalDateTime, JSON, JSON, JSON, LocalDateTime, LocalDateTime, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row21) super.fieldsRow();
    }
}
