/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.RecipeJson;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeJsonRecord extends UpdatableRecordImpl<RecipeJsonRecord> implements Record4<Integer, JSON, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.recipe_json.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.recipe_json.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.recipe_json.recipe_json</code>.
     */
    public void setRecipeJson(JSON value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.recipe_json.recipe_json</code>.
     */
    public JSON getRecipeJson() {
        return (JSON) get(1);
    }

    /**
     * Setter for <code>public.recipe_json.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.recipe_json.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.recipe_json.to_obj</code>.
     */
    public void setToObj(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.recipe_json.to_obj</code>.
     */
    public Boolean getToObj() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, JSON, LocalDateTime, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, JSON, LocalDateTime, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RecipeJson.RECIPE_JSON.ID;
    }

    @Override
    public Field<JSON> field2() {
        return RecipeJson.RECIPE_JSON.RECIPE_JSON_;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return RecipeJson.RECIPE_JSON.INSERT_TIME;
    }

    @Override
    public Field<Boolean> field4() {
        return RecipeJson.RECIPE_JSON.TO_OBJ;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public JSON component2() {
        return getRecipeJson();
    }

    @Override
    public LocalDateTime component3() {
        return getInsertTime();
    }

    @Override
    public Boolean component4() {
        return getToObj();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public JSON value2() {
        return getRecipeJson();
    }

    @Override
    public LocalDateTime value3() {
        return getInsertTime();
    }

    @Override
    public Boolean value4() {
        return getToObj();
    }

    @Override
    public RecipeJsonRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RecipeJsonRecord value2(JSON value) {
        setRecipeJson(value);
        return this;
    }

    @Override
    public RecipeJsonRecord value3(LocalDateTime value) {
        setInsertTime(value);
        return this;
    }

    @Override
    public RecipeJsonRecord value4(Boolean value) {
        setToObj(value);
        return this;
    }

    @Override
    public RecipeJsonRecord values(Integer value1, JSON value2, LocalDateTime value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipeJsonRecord
     */
    public RecipeJsonRecord() {
        super(RecipeJson.RECIPE_JSON);
    }

    /**
     * Create a detached, initialised RecipeJsonRecord
     */
    public RecipeJsonRecord(Integer id, JSON recipeJson, LocalDateTime insertTime, Boolean toObj) {
        super(RecipeJson.RECIPE_JSON);

        setId(id);
        setRecipeJson(recipeJson);
        setInsertTime(insertTime);
        setToObj(toObj);
    }
}
