/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.TbGoods;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbGoodsRecord extends UpdatableRecordImpl<TbGoodsRecord> implements Record11<Integer, String, String, Integer, String, Integer, Integer, JSON, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_goods.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_goods.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_goods.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_goods.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_goods.desc</code>.
     */
    public void setDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_goods.desc</code>.
     */
    public String getDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_goods.cate</code>.
     */
    public void setCate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_goods.cate</code>.
     */
    public Integer getCate() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tb_goods.sub_cate</code>.
     */
    public void setSubCate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_goods.sub_cate</code>.
     */
    public String getSubCate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_goods.remain_batch</code>.
     */
    public void setRemainBatch(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_goods.remain_batch</code>.
     */
    public Integer getRemainBatch() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tb_goods.recent_price</code>.
     */
    public void setRecentPrice(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_goods.recent_price</code>.
     */
    public Integer getRecentPrice() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tb_goods.images</code>.
     */
    public void setImages(JSON value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tb_goods.images</code>.
     */
    public JSON getImages() {
        return (JSON) get(7);
    }

    /**
     * Setter for <code>public.tb_goods.need_buy</code>.
     */
    public void setNeedBuy(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tb_goods.need_buy</code>.
     */
    public Integer getNeedBuy() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tb_goods.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tb_goods.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.tb_goods.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tb_goods.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, Integer, String, Integer, Integer, JSON, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, Integer, String, Integer, Integer, JSON, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbGoods.TB_GOODS.ID;
    }

    @Override
    public Field<String> field2() {
        return TbGoods.TB_GOODS.NAME;
    }

    @Override
    public Field<String> field3() {
        return TbGoods.TB_GOODS.DESC;
    }

    @Override
    public Field<Integer> field4() {
        return TbGoods.TB_GOODS.CATE;
    }

    @Override
    public Field<String> field5() {
        return TbGoods.TB_GOODS.SUB_CATE;
    }

    @Override
    public Field<Integer> field6() {
        return TbGoods.TB_GOODS.REMAIN_BATCH;
    }

    @Override
    public Field<Integer> field7() {
        return TbGoods.TB_GOODS.RECENT_PRICE;
    }

    @Override
    public Field<JSON> field8() {
        return TbGoods.TB_GOODS.IMAGES;
    }

    @Override
    public Field<Integer> field9() {
        return TbGoods.TB_GOODS.NEED_BUY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return TbGoods.TB_GOODS.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return TbGoods.TB_GOODS.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDesc();
    }

    @Override
    public Integer component4() {
        return getCate();
    }

    @Override
    public String component5() {
        return getSubCate();
    }

    @Override
    public Integer component6() {
        return getRemainBatch();
    }

    @Override
    public Integer component7() {
        return getRecentPrice();
    }

    @Override
    public JSON component8() {
        return getImages();
    }

    @Override
    public Integer component9() {
        return getNeedBuy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDesc();
    }

    @Override
    public Integer value4() {
        return getCate();
    }

    @Override
    public String value5() {
        return getSubCate();
    }

    @Override
    public Integer value6() {
        return getRemainBatch();
    }

    @Override
    public Integer value7() {
        return getRecentPrice();
    }

    @Override
    public JSON value8() {
        return getImages();
    }

    @Override
    public Integer value9() {
        return getNeedBuy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    @Override
    public TbGoodsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbGoodsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbGoodsRecord value3(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public TbGoodsRecord value4(Integer value) {
        setCate(value);
        return this;
    }

    @Override
    public TbGoodsRecord value5(String value) {
        setSubCate(value);
        return this;
    }

    @Override
    public TbGoodsRecord value6(Integer value) {
        setRemainBatch(value);
        return this;
    }

    @Override
    public TbGoodsRecord value7(Integer value) {
        setRecentPrice(value);
        return this;
    }

    @Override
    public TbGoodsRecord value8(JSON value) {
        setImages(value);
        return this;
    }

    @Override
    public TbGoodsRecord value9(Integer value) {
        setNeedBuy(value);
        return this;
    }

    @Override
    public TbGoodsRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TbGoodsRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TbGoodsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, Integer value7, JSON value8, Integer value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbGoodsRecord
     */
    public TbGoodsRecord() {
        super(TbGoods.TB_GOODS);
    }

    /**
     * Create a detached, initialised TbGoodsRecord
     */
    public TbGoodsRecord(Integer id, String name, String desc, Integer cate, String subCate, Integer remainBatch, Integer recentPrice, JSON images, Integer needBuy, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TbGoods.TB_GOODS);

        setId(id);
        setName(name);
        setDesc(desc);
        setCate(cate);
        setSubCate(subCate);
        setRemainBatch(remainBatch);
        setRecentPrice(recentPrice);
        setImages(images);
        setNeedBuy(needBuy);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
