/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.TbIngRecipeRel;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbIngRecipeRelRecord extends TableRecordImpl<TbIngRecipeRelRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public void setIid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.iid</code>.
     */
    public Integer getIid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public void setRid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.rid</code>.
     */
    public Integer getRid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public void setAmount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.amount</code>.
     */
    public String getAmount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public void setCat(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_ing_recipe_rel.cat</code>.
     */
    public String getCat() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.IID;
    }

    @Override
    public Field<Integer> field2() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.RID;
    }

    @Override
    public Field<String> field3() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.AMOUNT;
    }

    @Override
    public Field<String> field4() {
        return TbIngRecipeRel.TB_ING_RECIPE_REL.CAT;
    }

    @Override
    public Integer component1() {
        return getIid();
    }

    @Override
    public Integer component2() {
        return getRid();
    }

    @Override
    public String component3() {
        return getAmount();
    }

    @Override
    public String component4() {
        return getCat();
    }

    @Override
    public Integer value1() {
        return getIid();
    }

    @Override
    public Integer value2() {
        return getRid();
    }

    @Override
    public String value3() {
        return getAmount();
    }

    @Override
    public String value4() {
        return getCat();
    }

    @Override
    public TbIngRecipeRelRecord value1(Integer value) {
        setIid(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value2(Integer value) {
        setRid(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value3(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord value4(String value) {
        setCat(value);
        return this;
    }

    @Override
    public TbIngRecipeRelRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbIngRecipeRelRecord
     */
    public TbIngRecipeRelRecord() {
        super(TbIngRecipeRel.TB_ING_RECIPE_REL);
    }

    /**
     * Create a detached, initialised TbIngRecipeRelRecord
     */
    public TbIngRecipeRelRecord(Integer iid, Integer rid, String amount, String cat) {
        super(TbIngRecipeRel.TB_ING_RECIPE_REL);

        setIid(iid);
        setRid(rid);
        setAmount(amount);
        setCat(cat);
    }
}
