/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.TbIngredient;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbIngredientRecord extends UpdatableRecordImpl<TbIngredientRecord> implements Record3<Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_ingredient.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_ingredient.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_ingredient.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_ingredient.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_ingredient.insert_time</code>.
     */
    public void setInsertTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_ingredient.insert_time</code>.
     */
    public LocalDateTime getInsertTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbIngredient.TB_INGREDIENT.ID;
    }

    @Override
    public Field<String> field2() {
        return TbIngredient.TB_INGREDIENT.NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TbIngredient.TB_INGREDIENT.INSERT_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDateTime component3() {
        return getInsertTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDateTime value3() {
        return getInsertTime();
    }

    @Override
    public TbIngredientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbIngredientRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbIngredientRecord value3(LocalDateTime value) {
        setInsertTime(value);
        return this;
    }

    @Override
    public TbIngredientRecord values(Integer value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbIngredientRecord
     */
    public TbIngredientRecord() {
        super(TbIngredient.TB_INGREDIENT);
    }

    /**
     * Create a detached, initialised TbIngredientRecord
     */
    public TbIngredientRecord(Integer id, String name, LocalDateTime insertTime) {
        super(TbIngredient.TB_INGREDIENT);

        setId(id);
        setName(name);
        setInsertTime(insertTime);
    }
}
