/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.TbItem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbItemRecord extends UpdatableRecordImpl<TbItemRecord> implements Record15<Integer, Integer, String, String, String, String, Integer, String, Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached TbItemRecord
     */
    public TbItemRecord() {
        super(TbItem.TB_ITEM);
    }

    /**
     * Create a detached, initialised TbItemRecord
     */
    public TbItemRecord(Integer id, Integer goodId, String name, String images, String desc, String spec, Integer price, String isbn, Integer bestFavor, Integer shelfLife, String storage, String usedStorage, String remark, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TbItem.TB_ITEM);

        setId(id);
        setGoodId(goodId);
        setName(name);
        setImages(images);
        setDesc(desc);
        setSpec(spec);
        setPrice(price);
        setIsbn(isbn);
        setBestFavor(bestFavor);
        setShelfLife(shelfLife);
        setStorage(storage);
        setUsedStorage(usedStorage);
        setRemark(remark);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }

    /**
     * Getter for <code>public.tb_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_item.good_id</code>.
     */
    public Integer getGoodId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tb_item.good_id</code>.
     */
    public void setGoodId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_item.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_item.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_item.images</code>.
     */
    public String getImages() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_item.images</code>.
     */
    public void setImages(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_item.desc</code>.
     */
    public String getDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_item.desc</code>.
     */
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_item.spec</code>. 规格
     */
    public String getSpec() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_item.spec</code>. 规格
     */
    public void setSpec(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_item.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tb_item.price</code>.
     */
    public void setPrice(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_item.isbn</code>.
     */
    public String getIsbn() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_item.isbn</code>.
     */
    public void setIsbn(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tb_item.best_favor</code>. 最佳赏味（单位小时）
     */
    public Integer getBestFavor() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tb_item.best_favor</code>. 最佳赏味（单位小时）
     */
    public void setBestFavor(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tb_item.shelf_life</code>. 保质期（单位小时）
     */
    public Integer getShelfLife() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tb_item.shelf_life</code>. 保质期（单位小时）
     */
    public void setShelfLife(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tb_item.storage</code>. 推荐保存方式
     */
    public String getStorage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tb_item.storage</code>. 推荐保存方式
     */
    public void setStorage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tb_item.used_storage</code>. 拆分后保存方式
     */
    public String getUsedStorage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.tb_item.used_storage</code>. 拆分后保存方式
     */
    public void setUsedStorage(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tb_item.remark</code>.
     */
    public String getRemark() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tb_item.remark</code>.
     */
    public void setRemark(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tb_item.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.tb_item.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(13, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.tb_item.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.tb_item.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(14, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row15<Integer, Integer, String, String, String, String, Integer, String, Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, Integer, String, String, String, String, Integer, String, Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbItem.TB_ITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TbItem.TB_ITEM.GOOD_ID;
    }

    @Override
    public Field<String> field3() {
        return TbItem.TB_ITEM.NAME;
    }

    @Override
    public Field<String> field4() {
        return TbItem.TB_ITEM.IMAGES;
    }

    @Override
    public Field<String> field5() {
        return TbItem.TB_ITEM.DESC;
    }

    @Override
    public Field<String> field6() {
        return TbItem.TB_ITEM.SPEC;
    }

    @Override
    public Field<Integer> field7() {
        return TbItem.TB_ITEM.PRICE;
    }

    @Override
    public Field<String> field8() {
        return TbItem.TB_ITEM.ISBN;
    }

    @Override
    public Field<Integer> field9() {
        return TbItem.TB_ITEM.BEST_FAVOR;
    }

    @Override
    public Field<Integer> field10() {
        return TbItem.TB_ITEM.SHELF_LIFE;
    }

    @Override
    public Field<String> field11() {
        return TbItem.TB_ITEM.STORAGE;
    }

    @Override
    public Field<String> field12() {
        return TbItem.TB_ITEM.USED_STORAGE;
    }

    @Override
    public Field<String> field13() {
        return TbItem.TB_ITEM.REMARK;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return TbItem.TB_ITEM.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return TbItem.TB_ITEM.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGoodId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getImages();
    }

    @Override
    public String component5() {
        return getDesc();
    }

    @Override
    public String component6() {
        return getSpec();
    }

    @Override
    public Integer component7() {
        return getPrice();
    }

    @Override
    public String component8() {
        return getIsbn();
    }

    @Override
    public Integer component9() {
        return getBestFavor();
    }

    @Override
    public Integer component10() {
        return getShelfLife();
    }

    @Override
    public String component11() {
        return getStorage();
    }

    @Override
    public String component12() {
        return getUsedStorage();
    }

    @Override
    public String component13() {
        return getRemark();
    }

    @Override
    public LocalDateTime component14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component15() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGoodId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getImages();
    }

    @Override
    public String value5() {
        return getDesc();
    }

    @Override
    public String value6() {
        return getSpec();
    }

    @Override
    public Integer value7() {
        return getPrice();
    }

    @Override
    public String value8() {
        return getIsbn();
    }

    @Override
    public Integer value9() {
        return getBestFavor();
    }

    @Override
    public Integer value10() {
        return getShelfLife();
    }

    @Override
    public String value11() {
        return getStorage();
    }

    @Override
    public String value12() {
        return getUsedStorage();
    }

    @Override
    public String value13() {
        return getRemark();
    }

    @Override
    public LocalDateTime value14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value15() {
        return getUpdateTime();
    }

    @Override
    public TbItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbItemRecord value2(Integer value) {
        setGoodId(value);
        return this;
    }

    @Override
    public TbItemRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TbItemRecord value4(String value) {
        setImages(value);
        return this;
    }

    @Override
    public TbItemRecord value5(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public TbItemRecord value6(String value) {
        setSpec(value);
        return this;
    }

    @Override
    public TbItemRecord value7(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public TbItemRecord value8(String value) {
        setIsbn(value);
        return this;
    }

    @Override
    public TbItemRecord value9(Integer value) {
        setBestFavor(value);
        return this;
    }

    @Override
    public TbItemRecord value10(Integer value) {
        setShelfLife(value);
        return this;
    }

    @Override
    public TbItemRecord value11(String value) {
        setStorage(value);
        return this;
    }

    @Override
    public TbItemRecord value12(String value) {
        setUsedStorage(value);
        return this;
    }

    @Override
    public TbItemRecord value13(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public TbItemRecord value14(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TbItemRecord value15(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TbItemRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, Integer value7, String value8, Integer value9, Integer value10, String value11, String value12, String value13, LocalDateTime value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }
}
