/*
 * This file is generated by jOOQ.
 */
package com.theoxao.duraemon.orm.dto.tables.records;


import com.theoxao.duraemon.orm.dto.tables.TbLocation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbLocationRecord extends UpdatableRecordImpl<TbLocationRecord> implements Record7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_location.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_location.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_location.room</code>.
     */
    public void setRoom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_location.room</code>.
     */
    public String getRoom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_location.location</code>.
     */
    public void setLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_location.location</code>.
     */
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_location.loc_short</code>.
     */
    public void setLocShort(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_location.loc_short</code>.
     */
    public String getLocShort() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_location.loc_code</code>.
     */
    public void setLocCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_location.loc_code</code>.
     */
    public String getLocCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_location.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_location.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.tb_location.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_location.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbLocation.TB_LOCATION.ID;
    }

    @Override
    public Field<String> field2() {
        return TbLocation.TB_LOCATION.ROOM;
    }

    @Override
    public Field<String> field3() {
        return TbLocation.TB_LOCATION.LOCATION;
    }

    @Override
    public Field<String> field4() {
        return TbLocation.TB_LOCATION.LOC_SHORT;
    }

    @Override
    public Field<String> field5() {
        return TbLocation.TB_LOCATION.LOC_CODE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TbLocation.TB_LOCATION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TbLocation.TB_LOCATION.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRoom();
    }

    @Override
    public String component3() {
        return getLocation();
    }

    @Override
    public String component4() {
        return getLocShort();
    }

    @Override
    public String component5() {
        return getLocCode();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRoom();
    }

    @Override
    public String value3() {
        return getLocation();
    }

    @Override
    public String value4() {
        return getLocShort();
    }

    @Override
    public String value5() {
        return getLocCode();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateTime();
    }

    @Override
    public TbLocationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TbLocationRecord value2(String value) {
        setRoom(value);
        return this;
    }

    @Override
    public TbLocationRecord value3(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public TbLocationRecord value4(String value) {
        setLocShort(value);
        return this;
    }

    @Override
    public TbLocationRecord value5(String value) {
        setLocCode(value);
        return this;
    }

    @Override
    public TbLocationRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TbLocationRecord value7(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TbLocationRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbLocationRecord
     */
    public TbLocationRecord() {
        super(TbLocation.TB_LOCATION);
    }

    /**
     * Create a detached, initialised TbLocationRecord
     */
    public TbLocationRecord(Integer id, String room, String location, String locShort, String locCode, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TbLocation.TB_LOCATION);

        setId(id);
        setRoom(room);
        setLocation(location);
        setLocShort(locShort);
        setLocCode(locCode);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
